
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwmueglfbrpupcvydovk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3bXVlZ2xmYnJwdXBjdnlkb3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODQzMjksImV4cCI6MjA1OTg2MDMyOX0.edBdTK_kUNMcUJnTH22LAFTLZgjzTV6MpBtBhCgJxKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
